language: c

env:
  global:
    - CODECOV_TOKEN=36adeeb5-96db-45a9-a5ab-ad2d2cec0e40
    
compiler:
  - gcc

before_script:
  - ./install_deps.sh
  - export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH/usr/local/lib
  - export CFLAGS="-I`pwd`/include -L`pwd`/lib $CFLAGS"

  
script: pwd && ls && DO_COV_TEST=1 make install && make tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
